### ISSUE TITLE
sys tray app

### ISSUE THREAD

**Issue by reklis** [kennykerr/modern#10]
Not really an issue, more like a feature request?  The tool I am working on is a traditional systray app that  currently uses the traditional core win32 function calls and some rather ugly code to read ini files.  I'd like to start fresh with this, is there a way to create and register system tray windows with right click menus and such?  I looked around but I didn't see any specific documentation dealing with this. Thanks!

**Comment by kennykerr** [comment]
Thanks for the suggestion. I’ll keep it in mind.

Currently the Modern project only covers what’s available through the [Windows API for the Universal Windows Platform](https://msdn.microsoft.com/en-us/library/windows/apps/br211377.aspx).
