### ISSUE TITLE
The Windows 8.1 does'nt compiler

### ISSUE THREAD

**Issue by mediabuff** [kennykerr/modern#14]
The Windows 8.1 does'nt compiler either under MSVC 2013 or 2013 with toolset set to V120. Errors on c++ features like 'noexcept'. How do set templates for both Win81 and Win10 development.

**Comment by kennykerr** [comment]
Modern requires Visual C++ 2015 or later. I'm afraid I can't really help with project templates.

**Comment by mediabuff** [comment]
I have MSVC 2015.But how do develop for Windows 81. What settings do you use for compiling your Windows 8.1 headers ? Are you running Windows 10 ? I am running MSVC2015 on Windows 8.1

**Comment by mediabuff** [comment]
I tried the same on Windows 10 with MSVC 2015. Target platform Windows 8.1 Still, no luck. I wonder how you compiled your Windows 8.1 modern headers. You if could please kindly share your configuration, that will be grateful.

**Comment by mediabuff** [comment]
The moment you pick Windows 8.1 target (in MSVC2015, and MSVC2013 tools installed), it defaults to the 2013 c++ (major version 1800, minor version 180040620).  If the arget is Windows 10 universal app, it seems use 2015 c++ (major version 1900, minor version 190023026)

**Comment by mediabuff** [comment]
Just like you have sample for Windows 10, can you please provide a sample for Windows 8.1

**Comment by kennykerr** [comment]
You can try Modern's OCR and Syndication samples on Windows 8.1 - the main restriction is that you cannot use the Visual C++ 2015 compiler to create Store apps for Windows 8.1, however traditional desktop/console/component/service projects work just fine on Windows 8.1...

This is not a limitation in Modern but a restriction of the compiler itself. Modern is ultimately just a C++ library and you need a compiler to do the rest.

**Comment by mediabuff** [comment]
Thank you. That clarifies. The Windows 8.1 Modern header files are really for non-Store Win81 apps !!. MS too bad - perplexing why they don't let new Modern compiler for Win81 target.
