### ISSUE TITLE
Cannot compile 8.1 version with visual studio 2015

### ISSUE THREAD

**Issue by bilsou** [kennykerr/modern#16]

**Comment by kennykerr** [comment]
Thanks! You can build console and desktop apps using the Windows Runtime on Windows 8.1 - for store apps you'll need to prepare a custom toolchain which is considerably harder and I wouldn't suggest it.

**Comment by bilal-sou** [comment]
You're welcome, been looking at the source more in details and can only say, impressive.
Oh I see... I knew something was off when I saw the 8,1 version with all the new c++ features. Unfortunately I have a huge code base targeting 8.1 (phone an desktop) and can't just use the new toolset.. 
I was mostly interested in the awaitable features as after sepnding some time  to create that : 

	template <typename T>
	T Await(concurrency::task<T> t, concurrency::task_continuation_context continuationContext = concurrency::task_continuation_context::use_arbitrary())
	{
		HANDLE hEvent = CreateEventEx(nullptr, nullptr, CREATE_EVENT_MANUAL_RESET, EVENT_ALL_ACCESS);
		if (hEvent == nullptr)
		{
			throw std::bad_alloc();
		}

		T result;
		bool exceptionHandled = false;
		std::wstring exceptionMessage;
		t.then([&hEvent, &exceptionHandled, &exceptionMessage, &result](concurrency::task<T> previousTask)
		{
			try
			{
				result = previousTask.get();
			}
			catch (Platform::Exception^ ex)
			{
				exceptionHandled = true;
				exceptionMessage = std::wstring(ex->Message->Data());
				BE_Log("%s", exceptionMessage);
			}
			catch (std::exception & ex)
			{
				exceptionHandled = true;
				exceptionMessage = std::wstring(ex.what(), ex.what() + strlen(ex.what()));
				BE_Log("%s", exceptionMessage);
			}
			catch (...)
			{
				exceptionHandled = true;
				exceptionMessage = std::wstring(L"Unrecognized C++ exception.");
				BE_Log("%s", exceptionMessage);
			}
			SetEvent(hEvent);
		}, continuationContext).then(ObserveException<void>(g_exceptionPolicy));

		DWORD index;
		(void)CoWaitForMultipleHandles(COWAIT_DISPATCH_CALLS, INFINITE, 1, &hEvent, &index);

		if (hEvent != NULL)
		{
			// IMPORTANT : CloseHandle can hang depending on how the device's driver behaves 
			// http://blogs.msdn.com/b/meason/archive/2010/02/19/closehandle-hangs.aspx
			CloseHandle(hEvent);
		}

		return result;
	}

and after getting to the certification phase, CoWaitForMultipleHandles is no longer valid.. So basically have to change a really big chunk of my code as I need to wait on some processing (MediaCapture) to start before doing anything. I can't just rewrite the whole code base as it is huge and shared with iOS and Android. It's just crazy we can't use CoWaitForMultipleHandles anymore..

Anyway thanks again for your quick answer, I'll have to find another way to await on an asyn call...

B.

**Comment by kennykerr** [comment]
The await support requires the Visual C++ 2015 compiler. It is quite an improvement. :)

**Comment by bilal-sou** [comment]
Can't disagree with that, just not possible to switch to vs2015 for now unfortunately, 8.1 has still a HUGE market share. I'll have to find out some dirty COM way to replace my CoWaitForMultipleHandles

**Comment by kennykerr** [comment]
WaitForMultipleObjectsEx is available to store apps. Hope that helps.

**Comment by bilal-sou** [comment]
Not sure you can use WaitForMultipleObjectsEx  to wait on the main thread but yes definitely looking towards that. 
Thanks again, keep up the good work !
