### ISSUE TITLE
Project not available

### ISSUE THREAD

**Issue by samcov** [kennykerr/modern#2]
I'm sure this is something simple, but every project is unavailable and unloads.

I'm using VS2015 enterprise release with C++ installed, and the latest W10 SDK.

What am I missing?

**Comment by kennykerr** [comment]
You need to have Visual Studio 2015 with the optional C++ support and "Tools for Windows SDK 10.0.10240".

**Comment by samcov** [comment]
Visual Studio reports that C++ is installed, but it's not, you have to install C++ support first, then install Universal support which is under C# projects!

**Comment by kennykerr** [comment]
Yes the Visual Studio setup experience is a bit insane. 😊
