### ISSUE TITLE
Modern::Windows::UI::Xaml::Controls::Button - No Base of UIElement

### ISSUE THREAD

**Issue by brucebob** [kennykerr/modern#5]
void Modern::Windows::Foundation::Collections::impl_IVectorModern::Windows::Foundation::Collections::IVector<Modern::Windows::UI::Xaml::UIElement,T>::Append(const T &) const': cannot convert argument 1 from 'Modern::Windows::UI::Xaml::Controls::Button' to 'const Modern::Windows::UI::Xaml::UIElement &'

I can't bind it to a context as well.

**Comment by kennykerr** [comment]
Thanks for reporting. Looking into it now.

**Comment by kennykerr** [comment]
This should be fixed as of Modern v1.25. The parser was incorrectly parsing certain XAML class types. I'm not too familiar with XAML, so feel free to send me further examples if you experience any more problems.
