### ISSUE TITLE
Internal includes - forward slashes?

### ISSUE THREAD

**Issue by rpavlik** [kennykerr/modern#6]
Any way you can modify the generator tool to use forward slashes in the include statements? MSVC handles them fine, and then it increases the likelihood that other compilers and compilers hosted on other platforms can actually build the code.

**Comment by kennykerr** [comment]
It works with both VC and Clang. Do you have a concrete example for me? I doubt it would work with GCC even with the forward slashes, but I'd be happy for you to prove me wrong. :)

**Comment by rpavlik** [comment]
I was thinking cross-compiling with mxe, but you're right, I haven't actually tried it. I just make a habit of always using forward-slashes for portability.

**Comment by rpavlik** [comment]
Hmm, you're right - at least with the MinGW system includes, GCC can't build it (and it handles the backslashes OK). Pointing it at the 8.1 or 10 SDKs causes too many blowups to see what the first one was.
