### ISSUE TITLE
MapControl from Windows::UI::Xaml::Controls::Maps is absent

### ISSUE THREAD

**Issue by CVipulS** [kennykerr/modern#9]
Searching online gives the closest matching result at https://social.msdn.microsoft.com/Forums/en-US/f16482b7-5873-48e1-9c77-0d3f7fea716c/visual-studio-2015-uwp-the-name-mapcontrol-does-not-exist-in-the-namespace?forum=vssetup

**Comment by kennykerr** [comment]
It appears as if this namespace is only present in the platform metadata and not available in the Windows SDK (e.g. C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt). Currently, the Modern compiler requires type information to be provided by the Windows SDK. I'm considering changing the Modern compiler to parse the platform metadata directly.

**Comment by kennykerr** [comment]
You can find an update here: https://github.com/Microsoft/cppwinrt
